name: Deploy Doxygen to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Doxygen
        run: sudo apt-get install doxygen graphviz -y

      - name: Update Git Submodules
        run: git submodule init && git submodule update

      - name: Generate Doxygen Documentation
        run: doxygen Doxyfile

      # - name: Make Product FOlder
      #   run: >
      #     mkdir build && 
      #     cp -r docs build/ && 
      #     mv build/docs/html/* build/docs/ && 
      #     rm -rf build/docs/html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/html